default_language_version:
    python: python3
fail_fast: true
repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.1
    hooks:
    - id: pyupgrade
      stages: [commit]
      name: "✅ Python Upgrade"
      args:
        - "--py36-plus"
        - "--py37-plus"
        - "--py38-plus"
        - "--py39-plus"
        - "--py310-plus"
        - "--py311-plus"
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.16.0  # replace with latest tag on GitHub
    hooks:
    -   id: django-upgrade
        stages: [commit]
        name: "✅ Django Upgrade"
        args: [--target-version, "4.2"]
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
    - id: black
      stages: [commit]
      name: "✅ Black Reformatting"
      exclude: ^.*\b(migrations)\b.*$
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.0
    hooks:
    - id: autoflake
      stages: [commit]
      name: "✅ Autoflake Reformatting"
      language: python
      'types': [python]
      require_serial: true
      exclude: |
        (?x)(
          .*?/migrations/.* 
        )
      entry: autoflake
      args:
        - "--ignore-init-module-imports"
        - "--remove-all-unused-imports"
        - "--in-place"
        - "--remove-unused-variables"
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    - id: flake8
      stages: [commit]
      name: "✅ Flake8 Validation"
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
    - id: isort
      stages: [commit]
      name: "✅ Isort Validation"
  - repo: local
    hooks:
    - id: mypy
      stages: [commit]
      name: "✅ Mypy Validation"
      entry: mypy
      language: python
      types: [python]
      args: ["--install-types", "--non-interactive", "--python-version=3.11"]
      additional_dependencies: [
        "mypy~=0.931"
      ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the ref you want to point at
    hooks:
    - id: check-merge-conflict
      name: "✅ Checking Merge Conflict"
  - repo: local
    hooks:
    - id: django-test
      name: "🪲 Django Testing"
      entry: python runtests.py
      always_run: true
      verbose: true
      pass_filenames: false
      language: system